"""add pending_questions table

Revision ID: 5ed44c60f075
Revises: fa41393154b3
Create Date: 2026-05-31 23:32:23.825861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed44c60f075'
down_revision: Union[str, Sequence[str], None] = 'fa41393154b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('asked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_asked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_questions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_questions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_pending_questions_kind'))

    op.drop_table('pending_questions')
    # ### end Alembic commands ###
