"""baseline schema

Revision ID: fa41393154b3
Revises: 
Create Date: 2026-05-31 22:12:55.390069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa41393154b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_conditions', sa.Text(), nullable=True),
    sa.Column('markdown_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('goal_weight_kg', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('channel_preference', sa.String(), nullable=True),
    sa.Column('primary_goal', sa.String(), nullable=True),
    sa.Column('training_experience', sa.String(), nullable=True),
    sa.Column('dietary_preferences', sa.String(), nullable=True),
    sa.Column('injuries', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('webhook_token', sa.String(), nullable=True),
    sa.Column('whoop_access_token', sa.Text(), nullable=True),
    sa.Column('whoop_refresh_token', sa.Text(), nullable=True),
    sa.Column('whoop_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('whoop_user_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('units_preference', sa.String(), nullable=True),
    sa.Column('nudges_sent', sa.Text(), nullable=True),
    sa.Column('whoop_last_notified', sa.String(), nullable=True),
    sa.Column('weekly_recap_week', sa.String(), nullable=True),
    sa.Column('linked_to_user_id', sa.Integer(), nullable=True),
    sa.Column('link_code', sa.String(), nullable=True),
    sa.Column('link_code_expires', sa.DateTime(), nullable=True),
    sa.Column('active_mission', sa.String(), nullable=True),
    sa.Column('mission_metric', sa.String(), nullable=True),
    sa.Column('mission_target', sa.Float(), nullable=True),
    sa.Column('mission_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_webhook_token'), ['webhook_token'], unique=True)

    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bodyfat_estimate', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('photo_reference', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('parsed_intent', sa.String(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('skills_fired', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fats', sa.Float(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_water_ml', sa.Float(), nullable=True),
    sa.Column('workout_completed', sa.Boolean(), nullable=True),
    sa.Column('cardio_completed', sa.Boolean(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Float(), nullable=True),
    sa.Column('resting_calories', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_deep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_rem_hours', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('stand_hours', sa.Integer(), nullable=True),
    sa.Column('exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('recovery_score', sa.Integer(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('skin_temp_celsius', sa.Float(), nullable=True),
    sa.Column('spo2_percentage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('update_summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_food_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_norm', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('fdc_id', sa.String(), nullable=True),
    sa.Column('cal_100', sa.Float(), nullable=True),
    sa.Column('protein_100', sa.Float(), nullable=True),
    sa.Column('carbs_100', sa.Float(), nullable=True),
    sa.Column('fat_100', sa.Float(), nullable=True),
    sa.Column('fiber_100', sa.Float(), nullable=True),
    sa.Column('sugar_100', sa.Float(), nullable=True),
    sa.Column('sodium_100', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_food_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_food_matches_name_norm'), ['name_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_food_matches_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coaching_style', sa.String(), nullable=True),
    sa.Column('accountability_level', sa.String(), nullable=True),
    sa.Column('pacing_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_frequency', sa.String(), nullable=True),
    sa.Column('preferred_response_length', sa.String(), nullable=True),
    sa.Column('profanity_tolerance', sa.Boolean(), nullable=True),
    sa.Column('proactive_messaging_enabled', sa.Boolean(), nullable=True),
    sa.Column('wake_time', sa.String(), nullable=True),
    sa.Column('sleep_time', sa.String(), nullable=True),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target', sa.Integer(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wearable_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wearable_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('exercise_name', sa.String(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('cardio_type', sa.String(), nullable=True),
    sa.Column('calories_burned_estimate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('parsed_food_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('estimated_flag', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_entries')
    op.drop_table('exercise_entries')
    op.drop_table('wearable_metrics')
    op.drop_table('wearable_devices')
    op.drop_table('user_preferences')
    with op.batch_alter_table('user_food_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_food_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_food_matches_name_norm'))

    op.drop_table('user_food_matches')
    op.drop_table('memory_updates')
    op.drop_table('health_snapshots')
    op.drop_table('feedback')
    op.drop_table('daily_logs')
    op.drop_table('conversation_logs')
    op.drop_table('body_metrics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_webhook_token'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('skills')
    # ### end Alembic commands ###
