"""Food identity as an ID, with the aliases as data.

The corpus scores the string rule at one false match and five missed renames
out of 36 labelled pairs, and both failures are the same shape: a question
about IDENTITY answered by comparing SPELLING.

  * `potato` and `potatoes` are one food, and the rule says two, because it
    does not singularise — so the row is written twice.
  * `butter` and `peanut butter` are two foods, and the rule says one, because
    "butter" really is the head noun of "peanut butter". The rule is CORRECT
    and the answer is wrong, which is exactly why no further string rule fixes
    it: peanut butter is a distinct food that happens to be a butter.

Both dissolve once identity is an id. Two names are the same food when they
resolve to the same entity, and no amount of shared tokens makes them the same
if they do not.

WHAT THIS IS NOT, YET. It is not the full canonical entity registry the
directive describes — no nutrition linkage, no portion profiles, no restaurant
or product catalogue. It is the identity half, seeded from tables that already
exist, sized to close the measured failures and to give `_undeferred` something
to reconcile on. Rows are added as DATA; that is the acceptance criterion
("adding a synonym requires an alias entry, not changes across several
modules") and the reason this file is mostly a table.

SEEDED, NOT RE-AUTHORED. `PIECE_WEIGHTS_G` (59 rows) and `FOOD_CATEGORIES`
(111) already enumerate most of what users say. Copying them by hand would
create a seventh vocabulary that drifts; they are read at import instead.

ON GENERATED SPELLINGS. The directive is explicit that a generated form must
never become a semantic entity. Plurals here are expanded ONCE, at registry
construction, into an explicit alias index — they are stored data by the time
anything looks anything up, and a lookup never guesses. `potatoe` is not
generated by the expander and would resolve to nothing if it were typed.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Relation(str, Enum):
    """HOW one food relates to another. `parent_id` was carrying four of these
    at once, which the review caught before it became load-bearing.

    The distinction that matters for reconciliation is not hierarchy depth, it
    is whether the two are THE SAME FOOD when one describes the other better:

        alias_of            "potatoes" / "potato"        -> same
        subtype_of          "banana bread" / "bread"     -> same
        prepared_form_of    "grilled chicken" / "chicken"-> same
        product_variant_of  "greek yogurt" / "yogurt"    -> same
        ingredient_of       "chicken" / "chicken soup"   -> NOT the same
        distinct            "peanut butter" / "butter"   -> NOT the same

    `ingredient_of` is why one field was not enough. A soup CONTAINS chicken
    and IS a soup, and a model that can only say "related" would have to pick
    one — which is how "chicken" ends up claiming and deleting "chicken noodle
    soup", or the reverse.
    """
    ALIAS_OF = "alias_of"
    SUBTYPE_OF = "subtype_of"
    PREPARED_FORM_OF = "prepared_form_of"
    PRODUCT_VARIANT_OF = "product_variant_of"
    INGREDIENT_OF = "ingredient_of"
    DISTINCT = "distinct"


#: The relations under which two names denote ONE food, so a re-read naming
#: the narrower one may claim the wider. Everything else preserves both.
#: `INGREDIENT_OF` and `DISTINCT` are deliberately absent.
UNIFYING = frozenset({Relation.ALIAS_OF, Relation.SUBTYPE_OF,
                      Relation.PREPARED_FORM_OF, Relation.PRODUCT_VARIANT_OF})


@dataclass(frozen=True)
class EntityAlias:
    """One way a food is written, IN A LANGUAGE.

    English was baked into identity: aliases seeded from English tables,
    English plural rules, English preparation words stripped inside `resolve`.
    None of that is wrong for English and all of it is wrong as a definition of
    identity — "papa" is a potato in es-MX and nothing in the old shape could
    say so.

    Language travels with the alias so adding Spanish is rows rather than a
    second resolver.
    """
    text: str
    language: str = "en"
    locale: str = ""


@dataclass(frozen=True)
class FoodEntity:
    """One food, every way it is written, and how it relates to others.

    `relations` replaces `parent_id`. The old field answered "what is this a
    kind of?" and was asked to mean alias, subtype, preparation and product
    variant at once — four questions with one answer.
    """
    id: str
    canonical_name: str
    aliases: tuple = ()
    relations: tuple = ()          # ((Relation, target_entity_id), ...)

    @property
    def alias_texts(self) -> frozenset:
        return frozenset(a.text for a in self.aliases)

    def unifying_parents(self) -> tuple:
        return tuple(t for r, t in self.relations if r in UNIFYING)


#: (compound, relation, target). One row per fact, and the RELATION is the
#: fact — a bare parent could not tell "is a kind of" from "is made with".
#:
#: A FLAG WAS NOT ENOUGH AND NEITHER WAS A PARENT. The first version used a
#: boolean and scored eight wrong, because "banana bread" is not a banana AND
#: is a bread. A parent said both, and then quietly said four different things:
#: alias, subtype, preparation, product variant. `chicken` / `chicken noodle
#: soup` is the pair that forces the issue — the soup CONTAINS chicken and IS a
#: soup, and only one of those may unify.
_RELATIONS = (
    # is a kind of
    ("noodle soup", Relation.SUBTYPE_OF, "soup"),
    ("miso soup", Relation.SUBTYPE_OF, "soup"),
    ("chicken noodle soup", Relation.SUBTYPE_OF, "noodle soup"),
    ("banana bread", Relation.SUBTYPE_OF, "bread"),
    ("coffee cake", Relation.SUBTYPE_OF, "cake"),
    ("cream cheese", Relation.SUBTYPE_OF, "cheese"),
    ("apple pie", Relation.SUBTYPE_OF, "pie"),
    ("milk chocolate", Relation.SUBTYPE_OF, "chocolate"),
    ("egg roll", Relation.SUBTYPE_OF, "roll"),
    ("orange juice", Relation.SUBTYPE_OF, "juice"),
    ("chicken breast", Relation.SUBTYPE_OF, "chicken"),
    ("chicken thigh", Relation.SUBTYPE_OF, "chicken"),
    ("chicken wing", Relation.SUBTYPE_OF, "chicken"),
    ("olive oil", Relation.SUBTYPE_OF, "oil"),
    ("vegetable oil", Relation.SUBTYPE_OF, "oil"),
    ("coconut oil", Relation.SUBTYPE_OF, "oil"),
    ("cheddar cheese", Relation.SUBTYPE_OF, "cheese"),
    ("white rice", Relation.SUBTYPE_OF, "rice"),

    # cooked or otherwise prepared, still the same food
    ("fried rice", Relation.PREPARED_FORM_OF, "rice"),
    ("grilled chicken", Relation.PREPARED_FORM_OF, "chicken"),
    ("ground beef", Relation.PREPARED_FORM_OF, "beef"),
    ("ground turkey", Relation.PREPARED_FORM_OF, "turkey"),

    # a commercial or regional variant of the same food
    ("greek yogurt", Relation.PRODUCT_VARIANT_OF, "yogurt"),

    # MADE WITH, and therefore NOT the same food. These edges exist to be
    # refused: without them nothing records that the relationship was
    # considered, and the next person adds a parent.
    ("chicken noodle soup", Relation.INGREDIENT_OF, "chicken"),
    ("orange chicken", Relation.INGREDIENT_OF, "orange"),
    ("orange juice", Relation.INGREDIENT_OF, "orange"),
    ("banana bread", Relation.INGREDIENT_OF, "banana"),
    ("coffee cake", Relation.INGREDIENT_OF, "coffee"),
    ("apple pie", Relation.INGREDIENT_OF, "apple"),
    ("corn dog", Relation.INGREDIENT_OF, "corn"),
    ("milk chocolate", Relation.INGREDIENT_OF, "milk"),

    # nothing but itself — no food may claim these
    ("peanut butter", Relation.DISTINCT, ""),
    ("almond butter", Relation.DISTINCT, ""),
    ("eggplant parmesan", Relation.DISTINCT, ""),
    ("corn dog", Relation.DISTINCT, ""),
    ("hot dog", Relation.DISTINCT, ""),
    ("sweet potato", Relation.DISTINCT, ""),
    ("ice cream", Relation.DISTINCT, ""),
    ("sour cream", Relation.DISTINCT, ""),
    ("coconut water", Relation.DISTINCT, ""),
    ("water chestnut", Relation.DISTINCT, ""),
    ("buttermilk", Relation.DISTINCT, ""),
    ("rice cake", Relation.DISTINCT, ""),
    ("orange chicken", Relation.DISTINCT, ""),
)

#: Names the seeded tables do not carry, added as DATA. `berry` was the last
#: abstention on the corpus — the registry did not know it, so the delete path
#: preserved rather than collapsed. One row closes it, which is the point.
_EXTRA_NAMES = ("berry", "oil", "juice", "roll", "pie", "chocolate", "soup",
                "cake", "bread", "cheese", "yogurt", "beef", "turkey")


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", (name or "").strip().lower()).strip("_")


def _plural_forms(word: str) -> set:
    """The plural spellings of a canonical name, expanded ONCE at construction.

    Narrow on purpose. It produces the forms English actually uses and nothing
    else — no candidate-spelling generator, because the directive is explicit
    that a generated form must not become an entity, and because a generator
    is what produced "potatoe" in the first place.
    """
    w = (word or "").strip()
    if not w:
        return set()
    head, sep, tail = w.rpartition(" ")
    def _p(x):
        if re.search(r"(?:s|x|z|ch|sh)$", x):
            return x + "es"
        if re.search(r"[^aeiou]o$", x):
            return x + "es"
        if re.search(r"[^aeiou]y$", x):
            return x[:-1] + "ies"
        return x + "s"
    # Compounds pluralise their HEAD noun: "sweet potato" -> "sweet potatoes".
    return {f"{head}{sep}{_p(tail)}" if sep else _p(w)}


def _build() -> tuple:
    """Registry + alias index, from the tables that already exist."""
    from skills.nutrition.normalize import PIECE_WEIGHTS_G
    from skills.nutrition.portions import FOOD_CATEGORIES

    names: set = set(_EXTRA_NAMES)
    names.update(PIECE_WEIGHTS_G)
    # FOOD_CATEGORIES keys are FRAGMENTS ("blueberr", "cherr") as often as
    # names, so only whole-word entries are taken. A fragment is a matching
    # aid, not a food, and registering one as an entity would be the same
    # category error this module exists to correct.
    names.update(k for k in FOOD_CATEGORIES
                 if re.fullmatch(r"[a-z]+(?: [a-z]+)*", k) and len(k) > 3)
    for name, _rel, target in _RELATIONS:
        names.add(name)
        if target:
            names.add(target)

    by_name = {n: f"food:{_slug(n)}" for n in names}
    rels: dict = {}
    for name, rel, target in _RELATIONS:
        tid = by_name.get(target, "") if target else ""
        if rel is not Relation.DISTINCT and not tid:
            continue
        rels.setdefault(by_name[name], []).append((rel, tid))

    entities: dict = {}
    for name in sorted(names):
        eid = by_name[name]
        # English plurals are ALIASES, in English. They are expanded once, at
        # construction, into stored rows — a lookup never guesses a spelling.
        aliases = tuple(EntityAlias(text=t, language="en")
                        for t in sorted({name} | _plural_forms(name)))
        entities[eid] = FoodEntity(id=eid, canonical_name=name,
                                   aliases=aliases,
                                   relations=tuple(rels.get(eid, ())))

    index: dict = {}
    for ent in entities.values():
        for alias in ent.aliases:
            key = (alias.text, alias.language)
            cur = index.get(key)
            # LONGEST CANONICAL WINS a collision between two entities' alias
            # sets, so "sweet potatoes" resolves to the sweet potato rather
            # than to the potato whose plural it also contains.
            if cur is None or len(entities[cur].canonical_name) < \
                    len(ent.canonical_name):
                index[key] = ent.id
    return entities, index


def _form_words(language: str = "en") -> frozenset:
    """Words describing how a food was PREPARED rather than which food it is.

    KEYED BY LANGUAGE. Baking English cooking words into `resolve` made
    identity English-shaped; a language with no entry gets an empty set, so its
    names are matched whole and nothing is silently stripped.
    """
    if language != "en":
        return frozenset()
    try:
        from skills.nutrition.portions import FORM_ALIASES
        out = set()
        for alias in FORM_ALIASES:
            out.update(alias.split())
        return frozenset(out | {"grilled", "baked", "fried", "roasted"})
    except Exception:
        return frozenset({"cooked", "raw", "grilled", "baked", "fried",
                          "roasted", "boiled", "steamed"})


_ENTITIES, _ALIAS_INDEX = _build()


def resolve(name: str, language: str = "en") -> Optional[str]:
    """The entity id this name denotes, or None.

    NONE IS A REAL ANSWER and callers must treat it as one. Forcing a match is
    how a false one acquires a piece weight, merges two foods, or overwrites a
    correction target — and on the delete path `_claims_the_same_food` now
    treats None as "preserve both".

    LANGUAGE IS A PARAMETER, not an assumption. Everything English-specific —
    the plural expansion, the preparation vocabulary — is scoped to `language`,
    so adding Spanish is alias rows plus a form list rather than a second
    resolver. Punctuation stripping is the one step applied to every language,
    because "White rice, cooked" and "arroz blanco, cocido" both arrive with
    commas.
    """
    n = " ".join(re.sub(r"[^\w ]+", " ", (name or "").lower()).split())
    if not n:
        return None
    hit = _tail_match(n, language)
    if hit:
        return hit
    # PREPARATION IS NOT IDENTITY. "White rice, cooked" is a rice; the form
    # word sits where the head noun would be, so the tail match cannot see past
    # it. Tried only AFTER the whole name fails, so entities that genuinely
    # contain a form word keep it — "fried rice" is matched whole above and
    # never reduced to "rice".
    forms = _form_words(language)
    stripped = [w for w in n.split() if w not in forms]
    if stripped and len(stripped) != len(n.split()):
        return _tail_match(" ".join(stripped), language)
    return None


def _tail_match(n: str, language: str = "en") -> Optional[str]:
    """The longest registered phrase that is the HEAD of this name.

    English compounds put the head last, so "grilled chicken" resolves to
    chicken while "banana bread" does not resolve to banana. That rule is
    ENGLISH, which is why it is reached through a language-keyed index — a
    language whose compounds head differently needs its own matcher, not a
    patch to this one.
    """
    if (n, language) in _ALIAS_INDEX:
        return _ALIAS_INDEX[(n, language)]
    words = n.split()
    for size in range(len(words), 0, -1):
        tail = " ".join(words[-size:])
        if (tail, language) in _ALIAS_INDEX:
            return _ALIAS_INDEX[(tail, language)]
    return None


def get(entity_id: str) -> Optional[FoodEntity]:
    return _ENTITIES.get(entity_id)


def relation_between(a: str, b: str) -> Optional[Relation]:
    """The declared relation from `b` to `a`, if one is recorded.

    Reported so a caller can act on WHY rather than only on whether — an
    ingredient edge and an unknown pair both mean "do not claim", but only one
    of them means "we looked at this".
    """
    ea, eb = resolve(a), resolve(b)
    if ea is None or eb is None:
        return None
    ent = _ENTITIES.get(eb)
    for rel, target in (ent.relations if ent else ()):
        if target == ea:
            return rel
    return None


def ancestry(entity_id: str) -> tuple:
    """`entity_id` and every food it is the same food as, nearest first.

    Only UNIFYING relations are walked. An `ingredient_of` edge is recorded and
    deliberately not followed: chicken noodle soup is made with chicken and is
    not chicken, and walking that edge is how a soup claims and deletes it.

    Bounded against a cycle: the table is hand-maintained and a loop in it must
    degrade to a short chain rather than hang the turn.
    """
    seen, chain, frontier = set(), [], [entity_id]
    while frontier:
        cur = frontier.pop()
        if not cur or cur in seen:
            continue
        seen.add(cur)
        chain.append(cur)
        ent = _ENTITIES.get(cur)
        if ent:
            frontier.extend(ent.unifying_parents())
    return tuple(chain)


def same_food(a: str, b: str, language: str = "en") -> Optional[bool]:
    """True/False when both names resolve; None when either does not.

    Same food when they are the same entity, or when one is the other under a
    UNIFYING relation — alias, subtype, prepared form, product variant. An
    `ingredient_of` edge returns False: it is a recorded relationship AND a
    refusal, which is the distinction a bare parent could not express.

    THE THREE-VALUED RETURN IS THE POINT. A caller that cannot tell "different"
    from "I do not know" will treat the second as the first, and the failure
    being fixed is a confident answer to an unanswerable question.
    """
    ea, eb = resolve(a, language), resolve(b, language)
    if ea is None or eb is None:
        return None
    return ea in ancestry(eb) or eb in ancestry(ea)


def stands_alone(name: str) -> bool:
    """Whether this food is declared DISTINCT — nothing may claim it."""
    ent = _ENTITIES.get(resolve(name) or "")
    return bool(ent and any(r is Relation.DISTINCT for r, _ in ent.relations))


def coverage() -> dict:
    """How much vocabulary is registered. Should rise across phases."""
    from collections import Counter
    rels = Counter(r.value for e in _ENTITIES.values() for r, _ in e.relations)
    langs = Counter(lang for _t, lang in _ALIAS_INDEX)
    return {"entities": len(_ENTITIES), "aliases": len(_ALIAS_INDEX),
            "relations": dict(rels), "languages": dict(langs)}
