"""Food identity as an ID, with the aliases as data.

The corpus scores the string rule at one false match and five missed renames
out of 36 labelled pairs, and both failures are the same shape: a question
about IDENTITY answered by comparing SPELLING.

  * `potato` and `potatoes` are one food, and the rule says two, because it
    does not singularise — so the row is written twice.
  * `butter` and `peanut butter` are two foods, and the rule says one, because
    "butter" really is the head noun of "peanut butter". The rule is CORRECT
    and the answer is wrong, which is exactly why no further string rule fixes
    it: peanut butter is a distinct food that happens to be a butter.

Both dissolve once identity is an id. Two names are the same food when they
resolve to the same entity, and no amount of shared tokens makes them the same
if they do not.

WHAT THIS IS NOT, YET. It is not the full canonical entity registry the
directive describes — no nutrition linkage, no portion profiles, no restaurant
or product catalogue. It is the identity half, seeded from tables that already
exist, sized to close the measured failures and to give `_undeferred` something
to reconcile on. Rows are added as DATA; that is the acceptance criterion
("adding a synonym requires an alias entry, not changes across several
modules") and the reason this file is mostly a table.

SEEDED, NOT RE-AUTHORED. `PIECE_WEIGHTS_G` (59 rows) and `FOOD_CATEGORIES`
(111) already enumerate most of what users say. Copying them by hand would
create a seventh vocabulary that drifts; they are read at import instead.

ON GENERATED SPELLINGS. The directive is explicit that a generated form must
never become a semantic entity. Plurals here are expanded ONCE, at registry
construction, into an explicit alias index — they are stored data by the time
anything looks anything up, and a lookup never guesses. `potatoe` is not
generated by the expander and would resolve to nothing if it were typed.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional


@dataclass(frozen=True)
class FoodEntity:
    """One food, and every way it is written.

    `parent_id` is the whole answer to peanut butter, and to banana bread,
    which need OPPOSITE answers about the same shape. It records what the food
    IS, so a name that merely appears inside it can never claim it. That is
    data about the food, which is why it lives here rather than as a negative
    case in a matcher.
    """
    id: str
    canonical_name: str
    aliases: frozenset = frozenset()
    display_singular: str = ""
    display_plural: str = ""
    #: The food this one IS a kind of, if any. `""` means it stands alone —
    #: nothing may claim it by sharing a token with it.
    parent_id: str = ""


#: Compounds, and the food each one actually IS.
#:
#: A FLAG WAS NOT ENOUGH, and the corpus proved it in one run. The first
#: version marked "banana bread", "noodle soup" and "fried rice" as protected
#: compounds — and scored 8 wrong, because those ARE their head noun. Banana
#: bread is not a banana AND IS a bread. Both halves are true at once, and a
#: boolean can only say one of them.
#:
#: A parent says both. The entity is distinct from every food it merely
#: mentions, and identical in kind to the one it descends from:
#:
#:     banana bread   parent=bread    -> not a banana, is a bread
#:     peanut butter  parent=None     -> not a butter, is its own food
#:     noodle soup    parent=soup     -> is a soup
#:     orange juice   parent=juice    -> not an orange
#:
#: `parent=None` is the strong claim and is used sparingly: it says this food
#: is nothing but itself, so nothing may ever claim it. Peanut butter earns it
#: because it is a distinct food that happens to be spelled as a butter — the
#: exact case no string rule can reach.
_COMPOUND_PARENTS = {
    # is a kind of its head noun
    "noodle soup": "soup",
    "miso soup": "soup",
    "chicken noodle soup": "noodle soup",
    "fried rice": "rice",
    "white rice": "rice",
    "banana bread": "bread",
    "coffee cake": "cake",
    "cream cheese": "cheese",
    "chicken breast": "chicken",
    "chicken thigh": "chicken",
    "chicken wing": "chicken",
    "ground beef": "beef",
    "ground turkey": "turkey",
    "orange chicken": "chicken",
    "apple pie": "pie",
    "milk chocolate": "chocolate",
    "egg roll": "roll",
    "orange juice": "juice",
    # Added as DATA when the delete path stopped guessing and these two showed
    # up as abstentions. That is the acceptance criterion working: closing a
    # gap is a row here, not a change to a matching algorithm.
    "olive oil": "oil",
    "vegetable oil": "oil",
    "coconut oil": "oil",
    "greek yogurt": "yogurt",
    "cheddar cheese": "cheese",
    "grilled chicken": "chicken",
    # nothing but itself — no food may claim these
    "peanut butter": None,
    "almond butter": None,
    "eggplant parmesan": None,
    "corn dog": None,
    "hot dog": None,
    "sweet potato": None,
    "ice cream": None,
    "sour cream": None,
    "coconut water": None,
    "water chestnut": None,
    "buttermilk": None,
    "rice cake": None,
    "rice cakes": None,
}


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", (name or "").strip().lower()).strip("_")


def _plural_forms(word: str) -> set:
    """The plural spellings of a canonical name, expanded ONCE at construction.

    Narrow on purpose. It produces the forms English actually uses and nothing
    else — no candidate-spelling generator, because the directive is explicit
    that a generated form must not become an entity, and because a generator
    is what produced "potatoe" in the first place.
    """
    w = (word or "").strip()
    if not w:
        return set()
    head, sep, tail = w.rpartition(" ")
    def _p(x):
        if re.search(r"(?:s|x|z|ch|sh)$", x):
            return x + "es"
        if re.search(r"[^aeiou]o$", x):
            return x + "es"
        if re.search(r"[^aeiou]y$", x):
            return x[:-1] + "ies"
        return x + "s"
    # Compounds pluralise their HEAD noun: "sweet potato" -> "sweet potatoes".
    return {f"{head}{sep}{_p(tail)}" if sep else _p(w)}


def _build() -> tuple:
    """Registry + alias index, from the tables that already exist."""
    from skills.nutrition.normalize import PIECE_WEIGHTS_G
    from skills.nutrition.portions import FOOD_CATEGORIES

    names: set = set()
    names.update(k for k in PIECE_WEIGHTS_G)
    # FOOD_CATEGORIES keys are FRAGMENTS ("blueberr", "cherr") as often as
    # names, so only whole-word entries are taken. A fragment is a matching
    # aid, not a food, and registering one as an entity would be the same
    # category error this module exists to correct.
    names.update(k for k in FOOD_CATEGORIES
                 if re.fullmatch(r"[a-z]+(?: [a-z]+)*", k) and len(k) > 3)
    names.update(_COMPOUND_PARENTS)
    names.update(v for v in _COMPOUND_PARENTS.values() if v)

    entities: dict = {}
    for name in sorted(names):
        eid = f"food:{_slug(name)}"
        plurals = _plural_forms(name)
        entities[eid] = FoodEntity(
            id=eid,
            canonical_name=name,
            aliases=frozenset({name} | plurals),
            display_singular=name,
            display_plural=next(iter(plurals), name),
            parent_id=(f"food:{_slug(_COMPOUND_PARENTS[name])}"
                       if _COMPOUND_PARENTS.get(name) else ""),
        )

    index: dict = {}
    for ent in entities.values():
        for alias in ent.aliases:
            # LONGEST CANONICAL WINS a collision between two entities' alias
            # sets, so "sweet potatoes" resolves to the sweet potato rather
            # than to the potato whose plural it also contains.
            cur = index.get(alias)
            if cur is None or len(entities[cur].canonical_name) < \
                    len(ent.canonical_name):
                index[alias] = ent.id
    return entities, index


#: Words that describe how a food was PREPARED rather than which food it is.
#: Read from the ontology's own form vocabulary — a seventh hand-written list
#: of cooking words is exactly what this module exists to stop.
def _form_words() -> frozenset:
    try:
        from skills.nutrition.portions import FORM_ALIASES
        out = set()
        for alias in FORM_ALIASES:
            out.update(alias.split())
        return frozenset(out | {"grilled", "baked", "fried", "roasted"})
    except Exception:
        return frozenset({"cooked", "raw", "grilled", "baked", "fried",
                          "roasted", "boiled", "steamed"})


_ENTITIES, _ALIAS_INDEX = _build()
_FORM_WORDS = _form_words()


def resolve(name: str) -> Optional[str]:
    """The entity id this name denotes, or None.

    NONE IS A REAL ANSWER and the callers must treat it as one. Forcing a match
    is how a false one acquires a piece weight, merges two foods, or overwrites
    a correction target — the directive's "unknown is safer than a false match",
    and the reason this returns Optional rather than a best guess.

    Longest phrase first, so "peanut butter" is found before "butter" and
    "chicken noodle soup" before "chicken". That ordering IS the protected
    compound rule at lookup time; `protected_compound` records it on the entity
    so callers can also ask.
    """
    # Punctuation is not identity. Real names arrive as "White rice, cooked"
    # and "chicken (grilled)", and a comma was enough to make the whole lookup
    # miss — so it is normalised away before anything is compared, and NOT by
    # the callers, each of which would do it differently.
    n = " ".join(re.sub(r"[^a-z0-9 ]+", " ", (name or "").lower()).split())
    if not n:
        return None
    if n in _ALIAS_INDEX:
        return _ALIAS_INDEX[n]
    # Then the longest registered phrase that is the HEAD of this name, so
    # "grilled chicken" resolves to chicken while "banana bread" does not
    # resolve to banana.
    hit = _tail_match(n)
    if hit:
        return hit
    # PREPARATION IS NOT IDENTITY. "White rice, cooked" and "chicken (grilled)"
    # are a rice and a chicken; the form word is a fact ABOUT the food, and it
    # sits where the head noun would be, so the tail match cannot see past it.
    #
    # Tried only AFTER the whole name fails, so entities that genuinely contain
    # a form word keep it: "fried rice" is matched whole above and never
    # reaches here to be reduced to "rice".
    stripped = [w for w in n.split() if w not in _FORM_WORDS]
    if stripped and len(stripped) != len(n.split()):
        return _tail_match(" ".join(stripped))
    return None


def _tail_match(n: str) -> Optional[str]:
    """The longest registered phrase that is the HEAD of this name.

    English compounds put the head last, so "grilled chicken" resolves to
    chicken while "banana bread" does not resolve to banana — the bread is the
    head and the banana is a modifier.
    """
    if n in _ALIAS_INDEX:
        return _ALIAS_INDEX[n]
    words = n.split()
    for size in range(len(words), 0, -1):
        tail = " ".join(words[-size:])
        if tail in _ALIAS_INDEX:
            return _ALIAS_INDEX[tail]
    return None


def get(entity_id: str) -> Optional[FoodEntity]:
    return _ENTITIES.get(entity_id)


def stands_alone(name: str) -> bool:
    """Whether this food is nothing but itself — no other food may claim it.

    True for peanut butter, false for banana bread. The pair is the reason a
    boolean flag was not enough: both CONTAIN another food's name, and only one
    of them is a kind of it.
    """
    eid = resolve(name)
    ent = _ENTITIES.get(eid) if eid else None
    return bool(ent and ent.canonical_name in _COMPOUND_PARENTS
                and not ent.parent_id)


def ancestry(entity_id: str) -> tuple:
    """`entity_id` and every food it is a kind of, nearest first.

    Bounded against a cycle in the data: a parent table is hand-maintained, and
    a loop in it must degrade to a short chain rather than hang the turn.
    """
    seen, chain = set(), []
    cur = entity_id
    while cur and cur not in seen:
        seen.add(cur)
        chain.append(cur)
        ent = _ENTITIES.get(cur)
        cur = ent.parent_id if ent else ""
    return tuple(chain)


def same_food(a: str, b: str) -> Optional[bool]:
    """True/False when both names resolve; None when either does not.

    Same food when they are the same entity, OR when one is a kind of the
    other — "noodle soup" IS a soup, so a re-read naming it more precisely is
    one food described better rather than two foods.

    Descent is checked in BOTH directions because `_undeferred` sees two
    readings of one message and neither is guaranteed to be the narrower.

    THE THREE-VALUED RETURN IS THE POINT. A caller that cannot tell "these are
    different" from "I do not know" will treat the second as the first, and the
    failure being fixed is a confident answer to an unanswerable question. None
    means fall back to whatever the caller did before.
    """
    ea, eb = resolve(a), resolve(b)
    if ea is None or eb is None:
        return None
    return ea in ancestry(eb) or eb in ancestry(ea)


def coverage() -> dict:
    """How much of the vocabulary is registered. Should rise across phases."""
    return {"entities": len(_ENTITIES), "aliases": len(_ALIAS_INDEX),
            "with_parent": sum(1 for e in _ENTITIES.values() if e.parent_id),
            "stand_alone": sum(1 for e in _ENTITIES.values()
                               if e.canonical_name in _COMPOUND_PARENTS
                               and not e.parent_id)}
